<?php

/**
 * @file
 * Primary module hooks for Puffin Media module.
 */

/**
 * Implements hook_preprocess_responsive_image()
 */
function puffin_media_preprocess_responsive_image(&$variables) {
  $variables['img_element']['#responsive_image_style_id'] = $variables['responsive_image_style_id'];
}

/**
 * Implements hook_preprocess_image_style()
 */
function puffin_media_preprocess_image(&$variables) {

  //Add width & height attributes (depends on style_name core patch (07/22))
  if (isset($variables['responsive_image_style_id'])) {

    //Add Bootstrap classes to images
    $variables['attributes']['class'][] = 'w-100';
    $variables['attributes']['class'][] = 'h-auto';

    if (strpos($variables['responsive_image_style_id'],'5x4') !== FALSE) {
      $variables['attributes']['width'] = '500';
      $variables['attributes']['height'] = '400';
    }
    if (strpos($variables['responsive_image_style_id'],'16x9') !== FALSE) {
      $variables['attributes']['width'] = '1600';
      $variables['attributes']['height'] = '900';
    }
    if (strpos($variables['responsive_image_style_id'],'2x3') !== FALSE) {
      $variables['attributes']['width'] = '200';
      $variables['attributes']['height'] = '300';
    }    
    if (strpos($variables['responsive_image_style_id'],'3x1') !== FALSE) {
      $variables['attributes']['width'] = '300';
      $variables['attributes']['height'] = '100';
    }      
    if ($variables['responsive_image_style_id'] == 'hero') {
      $variables['attributes']['width'] = '500';
      $variables['attributes']['height'] = '400';
      $variables['attributes']['class'][] = 'heroImage';
    }
  }
}

/**
 * Implements hook_preprocess_field__media__videos() 
 */
function puffin_media_preprocess_field__media__videos(&$variables) {

  //Extract Youtube video id from media object
  $url = urldecode($variables["items"][0]["content"]["#attributes"]["src"]);

  preg_match('/\b[A-Za-z0-9_-]{11}\b/', $url, $video_id);

  $variables['video_id'] = $video_id[0];

}
